### ISSUE TITLE
DeepLabv3 pre-trained models

### ISSUE THREAD

**Issue by UndecidedBoy** [hkchengrex/Scribble-to-Mask#1]
Hello, 

I wanted to mention that in order to train S2M from scratch, using the `deeplabv3_resnet50` pre-trained model provided in this [repo](https://github.com/VainF/DeepLabV3Plus-Pytorch), returns the following error: `KeyError: 'classifier.classifier.0.convs.0.0.weight`.
Meaning that the weights from this layer are not present in `deeplabv3_resnet50`. But using the `deeplabv3plus_resnet50` from the same [repo](https://github.com/VainF/DeepLabV3Plus-Pytorch) executes without errors. 

Best!

**Comment by hkchengrex** [comment]
Thanks. Updated.
