### ISSUE TITLE
git.exc.InvalidGitRepositoryError when running train.py

### ISSUE THREAD

**Issue by whxueChris** [hkchengrex/Scribble-to-Mask#3]
Hello!  I followed the instruction of the training command, but it has thrown an error about GitRepositoryError.
![gitError](https://user-images.githubusercontent.com/50388024/156878202-02cf1b23-939b-4d4c-9a48-45ab73463eb2.JPG)
I used command : `CUDA_VISIBLE_DEVICES=0,1 OMP_NUM_THREADS=4 python -m torch.distributed.launch --master_port 1842 --nproc_per_node=2 train.py --id s2m --load_deeplab ./deeplab_resnet50/best_deeplabv3plus_resnet50_voc_os16.pth`, and I have 2 GPUs.
Could you give me some suggestions?

**Comment by hkchengrex** [comment]
Is the code in the valid git repository?

**Comment by whxueChris** [comment]
> 
Thanks for your reply! I have solved this problem using `git clone` to download this repository.
