### ISSUE TITLE
AttributeError: Caught AttributeError in DataLoader worker process 0

### ISSUE THREAD

**Issue by whxueChris** [hkchengrex/Scribble-to-Mask#4]
Hello! I followed the instructions of the training command, it has thrown an error about AttributeError.
![dataloader_error](https://user-images.githubusercontent.com/50388024/156906836-f43fdbe3-5fb6-4922-a76d-cd27749277dc.JPG)
I put the static folder outside this repository as you mentioned. It is confusing that I can use the same datasets for the pretraining propagation module, the train.py in Mask-Propagation works fine.

**Comment by hkchengrex** [comment]
You probably need this: https://stackoverflow.com/questions/57427233/module-cv2-cv2-has-no-attribute-ximgproc
Yeah they just use the same datasets because I did not put a lot of engineering in this module. It is just a simple baseline.

**Comment by whxueChris** [comment]
> You probably need this: https://stackoverflow.com/questions/57427233/module-cv2-cv2-has-no-attribute-ximgproc Yeah they just use the same datasets because I did not put a lot of engineering in this module. It is just a simple baseline.

Thank you! I followed the suggestion you gave and removed 2 OpenCV packages. It works fine
