### ISSUE TITLE
questions about range_transform.py

### ISSUE THREAD

**Issue by whxueChris** [hkchengrex/Scribble-to-Mask#5]
Hello !  Why im_mean was set to (124, 116, 104)?

**Comment by hkchengrex** [comment]
I used the imagenet mean: https://stackoverflow.com/questions/58151507/why-pytorch-officially-use-mean-0-485-0-456-0-406-and-std-0-229-0-224-0-2 and convert them to [0, 255] by multiplying each value with 255.
